
services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
  webapp1:
    restart: on-failure
    build: ./web
    hostname: webapp1
    ports:
      - '81:5000'
  webapp2:
    restart: on-failure
    build: ./web
    hostname: webapp2
    ports:
      - '82:5000'
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - webapp1
    - webapp2

